###################################
## General Settings

## These settings are standard Jekyll Settings, check the Jekyll docs for help

## Preprocessor settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

## Jekyll Serve
port: 4000

## Output
siteurl:                    ## Optional
baseurl:                    ## Optional
destination: _site          ## Output folder


###################################
## Style Guide Shell Settings

## These settings are used in when generating the style guide shell
sg_title: Aranda Device Management
sg_version: 3.0
sg_keywords: aranda, documentation, playbook, design, code
sg_description: Hacemos tu gestión de IT mucho más fácil
sg_language: es
sg_styles: /styleguide/css/styleguide.css
sg_favicon: /styleguide/branding/favicon.ico

## Generates Style Guide Shell Styles
## Enable to change the style guide shell stylesheet.
#sass:
#  sass_dir: styleguide/_scss
#  style: :compressed


###################################
## Collection Settings

## Outputs the _docs collection !Required
collections:
  docs:
    output: true

## Sets the default attributes for the Documentation and Pattern Files !Required
defaults:
  -
    scope:
      path: "_docs"
    values:
      layout: doc
      type: doc
  -
    scope:
      path: "_docs/instalacion"
    values:
      layout: doc
      type: instalacion
  -
    scope:
      path: "_docs/configuracion"
    values:
      layout: doc
      type: configuracion
  -
    scope:
      path: "_docs/agente"
    values:
      layout: doc
      type: agente
  -

###################################
## Pattern Settings
## These attributes are applied to all patterns via the pattern.html layout.

pattern_author: AUTHOR NAME             ## used in <head> tag
pattern_description: DESCRIPTION        ## used in <head> tag
pattern_language: en                    ## used in <html> tag
pattern_favicon: /src/assets/images/icon.ico
pattern_styles:                 ## add style locations here
  - /src/assets/css/style.css
pattern_scripts:                ## add script locations here
  - /src/assets/js/libs/jquery-2.1.4.min.js


## Generates Pattern Styles
## Disable to prevent pattern styles from being generated.
sass:
  sass_dir: src/assets/_scss
  style: :compressed
